name: TimeSeriesSimilarity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pandas=1.4.2
  - numpy=1.22.*
  - sktime-all-extras=0.11.3
  - tslearn=0.5.2
  - dtw-python=1.1.12
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - plotnine=0.9.0
  - matplotlib=3.5.1
  - glob2=0.7
  - ipykernel=6.9.1
  - pip
  - pip:
    - tssearch